### ISSUE TITLE
User detail page perms

### ISSUE THREAD

**Issue by church29** [OSU-Net/cyder#948]
Regression caused by https://github.com/OSU-Net/cyder/pull/901
As mentioned in a bug report:
|.......User Description......|
When wojcikc tries to log in he gets user access. When he clicks on his name he is directed to this error.

How to Reproduce:
1. Log in as wojcikc (possibly anyone with "user" access).
2. Click username in the top left.

Expected Result:
You should see your containers.

Actual Result:
You get a Django error stack trace:
AttributeError at /core/user/298/
'Token' object has no attribute 'get_ctnrs'
Request Method: GET
Request URL:    https://cyder.oregonstate.edu/core/user/298/
Django Version: 1.4.1
Exception Type: AttributeError
Exception Value:
'Token' object has no attribute 'get_ctnrs'
Exception Location:     /data/cyder/cyder/core/cyuser/backends.py in _has_perm, line 67

**Comment by murrown** [comment]
The bug occurs for any user that has an API token assigned to them.
